---

- hosts: all
  
  tasks:
   - name: create mdyson user
     user: name=mdyson shell=/bin/bash password=$6$C23sYB1e.E51t$rX8C7ufvhTD69MrbJLn23UPlG6zBMJsBJhmjdowuIlMbcumqF2seg7gaBWtbhV9zepKUn8O6Jj7b04w5kEOEC.
   - name: append user to sudo 
     lineinfile: dest=/etc/sudoers 
                 line='mdyson ALL=(ALL) NOPASSWD:ALL'
                 state=present
                 create=True 
   - name: Creates directory
     file: path=/home/mdyson/.ssh/ state=directory
   - name: create authorized_keys file for mdyson user
     lineinfile: dest=/home/mdyson/.ssh/authorized_keys 
                 line='ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCzTL0+7Atfo6y1C99350LHBbfid+2cSyRxw6A4lCdUjphv8vA7Cdfrl7kiwZKnLoj+MA+8kvSs3iFdizLD6e8DemIOdpfYw9vtB5OwZxYIcHD4Ygnw7CApZDA/sj9+xor+fTQgBggjrXMs6zbjdM3qEC6cUdww1wAQ+3bt5RCRE2k/uWi2+cKiKxNVpvVtNRwQIsPUl8fqwIVmCi2naMdvihDkfIFfeBZTVQ7LpX5qv3ZpTJErcHMi4YTabXJk1jbSxNY+Evmc//Dcm59cbllcyBsY94DijTPwmSngb55zc4eY3Hvvuitnx3P3GoKmSV10gKTW4Upm/nIeg30n9sdt ansible-generated on ceph-deploy'
                 state=present
                 create=True
   