---

- hosts: all
  
  tasks:
   - apt_key: url=https://ceph.com/git/?p=ceph.git;a=blob_plain;f=keys/release.asc state=present
   - apt_repository: repo='deb http://download.ceph.com/debian-jewel/ trusty main' state=present update_cache='yes'
   - apt: name='ceph-deploy' state='present' update_cache='yes'
   - name: create ceph user with id_rsa
     user: name=ceph generate_ssh_key=yes ssh_key_bits=2048 ssh_key_file=.ssh/id_rsa
   - name: add hosts to known hosts ssh_key_file
     shell: ssh-keyscan ods1.skyfall >> /home/ceph/.ssh/known_hosts
     shell: ssh-keyscan osd2.skyfall >> /home/ceph/.ssh/known_hosts
     shell: ssh-keyscan osd3.skyfall >> /home/ceph/.ssh/known_hosts
     shell: ssh-keyscan radosgw.skyfall >> /home/ceph/.ssh/known_hosts
     shell: ssh-keyscan client2.skyfall >> /home/ceph/.ssh/known_hosts
     shell: ssh-keyscan client3.skyfall >> /home/ceph/.ssh/known_hosts
     shell: ssh-keyscan client4.skyfall >> /home/ceph/.ssh/known_hosts