---

- hosts: all
  
  tasks:
   - name: create mdyson user
     user: name=mdyson shell=/bin/bash password=$6$C23sYB1e.E51t$rX8C7ufvhTD69MrbJLn23UPlG6zBMJsBJhmjdowuIlMbcumqF2seg7gaBWtbhV9zepKUn8O6Jj7b04w5kEOEC.
   - name: append user to sudo 
     lineinfile: dest=/etc/sudoers 
                 line='mdyson ALL=(ALL) NOPASSWD:ALL'
                 state=present
                 create=True 
   