---

- hosts: all
  
  tasks:
   - name: create mdyson user
     user: name=mdyson shell=/bin/bash password=$6$C23sYB1e.E51t$rX8C7ufvhTD69MrbJLn23UPlG6zBMJsBJhmjdowuIlMbcumqF2seg7gaBWtbhV9zepKUn8O6Jj7b04w5kEOEC.
   - name: append user to sudo 
     lineinfile: dest=/etc/sudoers 
                 line='mdyson ALL=(ALL) NOPASSWD:ALL'
                 state=present
                 create=True 
   - name: Creates directory
     file: path=/home/mdyson/.ssh/ state=directory
   - name: create authorized_keys file for mdyson user
     lineinfile: dest=/home/mdyson/.ssh/authorized_keys 
                 line='ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDCZZwhq23f9uUv/BtsRRUyVd2rEy1kRCHSU3TwTRcCRkx9O6WzzanvOW1QjJFRZXf3X3BQ7XVfc2EeBmUuyl61279r7q0BfQqtFhGaNHvYJAzpvRcCYMn6anUiQKF32ZaRvkmERiWwIu8E0XufzpUY9GCuj7AwtxpoLITBnba2GuKUFG/Eurz2610BS4a2SlyWVEPl4wUiGmA7dsPSZTYM4eWbqBjdAV/ZlhUey6v91Im8xYr5ScNiQNGXTjilEIWW23pDpAUfbjqkkMOJ5/XEQ2fHVxBjKK2JlMoprQtOvWYEtdwNn6Qi6mAQ7R1vzmrbYM/Aa1/Zs0KYGX+RDDVv ansible-generated on ceph-deploy'
                 state=present
                 create=True
   