---

- hosts: all
  
  tasks:
   - apt_key: url=https://ceph.com/git/?p=ceph.git;a=blob_plain;f=keys/release.asc state=present
   - apt_repository: repo='deb deb http://download.ceph.com/debian-jewel/trusty' state=present filename='jewel' update_cache='yes'
   - apt: name='ceph-deploy' state='present' update_cache='yes'
