---

- hosts: all
  
  tasks:
    - vsphere_guest:
        vcenter_hostname: 192.168.2.210
        username: administrator@vsphere.local
        password: password
        guest: newvm001
        state: powered_on
        vm_extra_config:
          vcpu.hotadd: yes
          mem.hotadd:  yes
          notes: This is a test VM
        vm_disk:
          disk1:
            size_gb: 10
            type: thin
            datastore: USB-Stick
        vm_nic:
          nic1:
            type: vmxnet3
            network: VM Network
            network_type: standard
        vm_hardware:
          memory_mb: 2048
          num_cpus: 2
          osid: centos64Guest
          scsi: paravirtual
          vm_cdrom:
            type: "iso"
            iso_path: "datastore7/iso/ubuntu-14.04-server-amd64.iso"
        esxi:
          datacenter: NTAC
          hostname: 192.168.2.201